### ISSUE TITLE
website wont load

### ISSUE THREAD

**Issue by SoupHuman** [corrosionwm/corrosionwm.github.io#5]
i wanted to look at the website, but it didnt load and eventually, i got a cloudflare error

screenshot:
![image](https://user-images.githubusercontent.com/77903666/232337079-120bf0e0-a978-432e-a8a7-6fcdf05d9fd2.png)

**Comment by electron271** [comment]
yeah the dns is borked atm, soon ill get to it

**Comment by electron271** [comment]
fixed
